// Shim → re-export from new SQLite-based DB layer (src/lib/db/)
// Kept for backward compatibility with existing imports.
export {
  getSettings, updateSettings, isCloudEnabled, getCloudUrl,
  getProviderConnections, getProviderConnectionById,
  createProviderConnection, updateProviderConnection,
  deleteProviderConnection, deleteProviderConnectionsByProvider,
  reorderProviderConnections, cleanupProviderConnections,
  getProviderNodes, getProviderNodeById,
  createProviderNode, updateProviderNode, deleteProviderNode,
  getProxyPools, getProxyPoolById,
  createProxyPool, updateProxyPool, deleteProxyPool,
  markProxyEntryCooldown,
  mutateProxyPoolEntries,
  stampProxyEntryUsed,
  setEntryCooldown,
  normalizeCooldownUntil,
  getApiKeys, getApiKeyById, createApiKey, updateApiKey, deleteApiKey, validateApiKey, rekeyApiKey, getApiKeyRow,
  getCombos, getComboById, getComboByName,
  createCombo, updateCombo, deleteCombo,
  getModelAliases, setModelAlias, deleteModelAlias,
  getCustomModels, addCustomModel, deleteCustomModel,
  getMitmAlias, setMitmAliasAll,
  getPricing, getPricingForModel, updatePricing, resetPricing, resetAllPricing,
  getXrayConfigs, getXrayConfigById, getXrayConfigByLink, getXrayConfigCounts, getXrayFacets,
  upsertXrayConfig, bulkUpsertXrayConfigs,
  markStaleXrayConfigs, deleteStaleXrayConfigs, cleanupStaleXrayConfigs, deleteXrayConfig, clearXrayConfigs,
  setSelectedXrayConfig, getSelectedXrayConfig, updateXrayTestResult,
  getXraySyncState, setXraySyncState,
  getModelFilterResult, getModelFilterResultsByConfigIds, getModelFilterCacheStats,
  getNextHealthyConfigsForModel,
  upsertModelFilterResult,
  clearModelFilterResultsByModel, clearAllModelFilterResults,
  deleteModelFilterResultsByConfigIds, pruneOrphanModelFilterResults,
  exportDb, importDb,
} from "@/lib/db/index.js";
